version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=asdf@123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=dJhC4VnRuYThfyWu8I6RtU6d5h94WaBXxveylJmu8Tx8kPCRKt17mdSuYcHbAAth0fv8DAeebUCGpebIPz63168QBjxJz4kVPCsKnoT1Oh7QRvFWiMpNsCIYP87odjVuHpbf2kO6aztUjXDa8NEA0XuxosoUwNR8fltuM6wOcvoHJByJ3OzSs1k6MLqWxZOFBGfbF8IxprnFYQEBFmT2IPRgJIYnPtGEY2up3aMhfcru5eaThrNTY0kJVwJ2bK05cmpNqUzSm72ojjB2gJmAxs62IDSaU1QJH2Muj2WNPUSLfeA5OcVxeILqvKeOC7C6
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
